name: spriggit-win
on:
  workflow_dispatch:
    inputs:
      branchname:
        description: 'Name of the new branch'
        required: true
        default: 'fix/test'
      message:
        description: 'Message for the commit'
        required: true
        default: 'Example fix'
      espfile:
        description: 'Source ESP/ESM File'
        required: true
        default: https://vtubertools.sfo3.digitaloceanspaces.com/LeafAyaJPV.esp
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Branch
        run: git checkout -b ${{ github.event.inputs.branchname }}
      - name: Download Source ESP
        run: iwr -outf ./source.esp "${{ github.event.inputs.espfile }}"
      - name: Run Spriggit
        run: ./.github/spriggit/Spriggit.CLI.exe serialize --InputPath "./source.esp" --OutputPath "./Data" --GameRelease SkyrimSE --PackageName Spriggit.Yaml
      - name: Commit and Push
        run: |
          git config --global user.name 'Spriggit'
          git config --global user.email 'sample@jetri.co'
          git add .
          git commit -m "${{ github.event.inputs.message }}"
          git push -u origin ${{ github.event.inputs.branchname }}
