name: spriggit
on:
  workflow_dispatch:
    inputs:
      branchname:
        description: 'Name of the new branch'
        required: true
        default: 'fix/'
      message:
        description: 'Message for the commit'
        required: true
        default: 'Auto-converted from ESP/ESM file'
      espfile:
        description: 'Source ESP/ESM File'
        required: true
        default: 'https://'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Branch
        run: git branch ${{ github.event.inputs.branchname }}
      - name: Run Spriggit
        run: node ./.github/spriggit/spriggit.js "${{ github.event.inputs.espfile }}"
      - name: Commit and Push
        run: |
          git config --global user.name 'Spriggit'
          git config --global user.email 'sample@jetri.co'
          git add .
          git commit -m "${{ github.event.inputs.message }}"
          git push
